# Configurare simplificată MelCloud pentru Home Assistant
# Adaugă în configuration.yaml

# 1. Input Number pentru flow temperature
input_number:
  melcloud_flow_temp:
    name: "MelCloud Flow Temperature"
    initial: 45
    min: 20
    max: 60
    step: 0.5
    unit_of_measurement: "°C"

# 2. Input Text pentru credențiale și date
input_text:
  melcloud_email:
    name: "MelCloud Email"
    initial: ""
  melcloud_password:
    name: "MelCloud Password"
    initial: ""
  melcloud_context_key:
    name: "MelCloud Context Key"
    initial: ""
  melcloud_device_id:
    name: "MelCloud Device ID"
    initial: ""
  melcloud_building_id:
    name: "MelCloud Building ID"
    initial: ""

# 3. REST Command pentru login
rest_command:
  melcloud_login:
    url: "https://app.melcloud.com/Mitsubishi.Wifi.Client/Login/ClientLogin"
    method: POST
    headers:
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
      Accept: "application/json, text/javascript, */*; q=0.01"
      Content-Type: "application/json"
      X-Requested-With: "XMLHttpRequest"
    payload: >
      {
        "Email": "{{ states('input_text.melcloud_email') }}",
        "Password": "{{ states('input_text.melcloud_password') }}",
        "Language": 0,
        "AppVersion": "1.19.1.1",
        "Persist": true,
        "CaptchaResponse": null
      }
    response_template: >
      {% if response.status == 200 %}
        {% set data = response.json() %}
        {% if data.ErrorId is none or data.ErrorId == null %}
          {{ data.LoginData.ContextKey }}
        {% else %}
          ERROR
        {% endif %}
      {% else %}
        ERROR
      {% endif %}

# 4. REST Command pentru setare flow temperature
rest_command:
  melcloud_set_temp:
    url: "https://app.melcloud.com/Mitsubishi.Wifi.Client/Device/SetAtw"
    method: POST
    headers:
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
      Accept: "application/json, text/javascript, */*; q=0.01"
      Content-Type: "application/json"
      X-MitsContextKey: "{{ states('input_text.melcloud_context_key') }}"
      X-Requested-With: "XMLHttpRequest"
      Cookie: "policyaccepted=true"
    payload: >
      {
        "DeviceID": {{ states('input_text.melcloud_device_id') | int }},
        "BuildingID": {{ states('input_text.melcloud_building_id') | int }},
        "SetHeatFlowTemperatureZone1": {{ states('input_number.melcloud_flow_temp') | float }}
      }

# 5. REST Command pentru citire date (va returna JSON)
rest_command:
  melcloud_get_data:
    url: "https://app.melcloud.com/Mitsubishi.Wifi.Client/Device/Get?id={{ states('input_text.melcloud_device_id') }}&buildingID={{ states('input_text.melcloud_building_id') }}"
    method: GET
    headers:
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
      Accept: "application/json, text/javascript, */*; q=0.01"
      X-MitsContextKey: "{{ states('input_text.melcloud_context_key') }}"
      X-Requested-With: "XMLHttpRequest"
      Cookie: "policyaccepted=true"
    response_template: "{{ response.json() }}"

# 6. Template Sensors pentru temperaturi (folosind rest_command)
template:
  - trigger:
      - platform: time_pattern
        minutes: /2  # La fiecare 2 minute
    sensor:
      - name: "MelCloud Temperature Tur"
        state: "{{ state_attr('sensor.melcloud_data', 'TankWaterTemperature') | default(state_attr('sensor.melcloud_data', 'RoomTemperatureZone1')) | float(0) }}"
        unit_of_measurement: "°C"
        device_class: temperature
        
      - name: "MelCloud Temperature Retur"
        state: >
          {% set temp = state_attr('sensor.melcloud_data', 'RoomTemperatureZone2') | float(0) %}
          {{ temp if temp != -39.0 else 'unavailable' }}
        unit_of_measurement: "°C"
        device_class: temperature
        
      - name: "MelCloud Temperature Exterioara"
        state: "{{ state_attr('sensor.melcloud_data', 'OutdoorTemperature') | float(0) }}"
        unit_of_measurement: "°C"
        device_class: temperature
        
      - name: "MelCloud Flow Temperature Set"
        state: "{{ state_attr('sensor.melcloud_data', 'SetHeatFlowTemperatureZone1') | default(state_attr('sensor.melcloud_data', 'SetCoolFlowTemperatureZone1')) | float(0) }}"
        unit_of_measurement: "°C"
        device_class: temperature

# 7. Automation pentru actualizare date periodic
automation:
  - alias: "MelCloud Get Data"
    trigger:
      - platform: time_pattern
        minutes: /2  # La fiecare 2 minute
    condition:
      - condition: template
        value_template: "{{ states('input_text.melcloud_context_key') != '' and states('input_text.melcloud_context_key') != 'ERROR' }}"
    action:
      - service: rest_command.melcloud_get_data
      - service: sensor.set_state
        entity_id: sensor.melcloud_data
        data_template:
          state: "{{ now().isoformat() }}"
          attributes: "{{ result | default({}) }}"

# 8. Automation pentru setare flow temperature
automation:
  - alias: "MelCloud Set Flow Temperature"
    trigger:
      - platform: state
        entity_id: input_number.melcloud_flow_temp
    condition:
      - condition: template
        value_template: "{{ states('input_text.melcloud_context_key') != '' and states('input_text.melcloud_context_key') != 'ERROR' }}"
    action:
      - service: rest_command.melcloud_set_temp

# 9. Script pentru login și salvare context key
script:
  melcloud_login:
    alias: "MelCloud Login"
    sequence:
      - service: rest_command.melcloud_login
      - service: input_text.set_value
        entity_id: input_text.melcloud_context_key
        data_template:
          value: "{{ result if result != 'ERROR' else '' }}"

